/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * Carmentis indexer API
 * Documentation for the Carmentis indexer API.
 * OpenAPI spec version: 1.0
 */
import type { EscrowLockDto } from './escrowLockDto';
import type { StakingLockDto } from './stakingLockDto';
import type { VestingLockDto } from './vestingLockDto';

export interface AccountDto {
  id: string;
  publicKey: string;
  height: number;
  balance: number;
  escrowLocks: EscrowLockDto[];
  vestingLocks: VestingLockDto[];
  stakingLocks: StakingLockDto[];
}
