/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * Carmentis indexer API
 * Documentation for the Carmentis indexer API.
 * OpenAPI spec version: 1.0
 */
import type { AccountDto } from './accountDto';

export interface AccountListResponseDto {
  items: AccountDto[];
  hasMore: boolean;
}
