/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * Carmentis indexer API
 * Documentation for the Carmentis indexer API.
 * OpenAPI spec version: 1.0
 */
import type { AccountHistoryDto } from './accountHistoryDto';

export interface AccountHistoryListResponseDto {
  items: AccountHistoryDto[];
  hasMore: boolean;
}
