/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * Carmentis indexer API
 * Documentation for the Carmentis indexer API.
 * OpenAPI spec version: 1.0
 */
import type { AccountProofWrapperDto } from './accountProofWrapperDto';

export interface AccountProofResponseDto {
  nodeUrl: string;
  proof: AccountProofWrapperDto;
}
