/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * Carmentis indexer API
 * Documentation for the Carmentis indexer API.
 * OpenAPI spec version: 1.0
 */

export type AppControllerGetGasPriceParams = {
/**
 * Minimum block height (inclusive)
 */
height_gte?: number;
/**
 * Maximum block height (inclusive)
 */
height_lte?: number;
};
