/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * Carmentis indexer API
 * Documentation for the Carmentis indexer API.
 * OpenAPI spec version: 1.0
 */

export type AppControllerGetVotingPowersSort = typeof AppControllerGetVotingPowersSort[keyof typeof AppControllerGetVotingPowersSort];


export const AppControllerGetVotingPowersSort = {
  height: 'height',
} as const;
