/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * Carmentis indexer API
 * Documentation for the Carmentis indexer API.
 * OpenAPI spec version: 1.0
 */
import type { AppControllerGetOrganizationsOrder } from './appControllerGetOrganizationsOrder';

export type AppControllerGetOrganizationsParams = {
/**
 * Sort order
 */
order?: AppControllerGetOrganizationsOrder;
/**
 * Limit number of results
 */
limit?: number;
/**
 * Virtual blockchain ID
 */
vb_id?: string;
/**
 * Account ID
 */
account_id?: string;
/**
 * Organization name
 */
name?: string;
};
