/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * Carmentis indexer API
 * Documentation for the Carmentis indexer API.
 * OpenAPI spec version: 1.0
 */
import type { AppControllerGetVirtualBlockchainsOrder } from './appControllerGetVirtualBlockchainsOrder';
import type { AppControllerGetVirtualBlockchainsSort } from './appControllerGetVirtualBlockchainsSort';

export type AppControllerGetVirtualBlockchainsParams = {
/**
 * Sort order
 */
order?: AppControllerGetVirtualBlockchainsOrder;
/**
 * Limit number of results
 */
limit?: number;
/**
 * Field on which the sort is applied
 */
sort?: AppControllerGetVirtualBlockchainsSort;
/**
 * Virtual blockchain ID
 */
vb_id?: string;
/**
 * Type
 */
type?: number;
};
