/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * Carmentis indexer API
 * Documentation for the Carmentis indexer API.
 * OpenAPI spec version: 1.0
 */
import type { AppControllerSearchOrder } from './appControllerSearchOrder';
import type { AppControllerSearchType } from './appControllerSearchType';

export type AppControllerSearchParams = {
/**
 * Sort order
 */
order?: AppControllerSearchOrder;
/**
 * Limit number of results
 */
limit?: number;
/**
 * Query string
 */
q: string;
/**
 * Type of object on which the search should focus
 */
type?: AppControllerSearchType;
};
