/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * Carmentis indexer API
 * Documentation for the Carmentis indexer API.
 * OpenAPI spec version: 1.0
 */

export type AppControllerGetBlocksOrder = typeof AppControllerGetBlocksOrder[keyof typeof AppControllerGetBlocksOrder];


export const AppControllerGetBlocksOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const;
