/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * Carmentis indexer API
 * Documentation for the Carmentis indexer API.
 * OpenAPI spec version: 1.0
 */

export type AppControllerGetOrganizationCertificatesOrder = typeof AppControllerGetOrganizationCertificatesOrder[keyof typeof AppControllerGetOrganizationCertificatesOrder];


export const AppControllerGetOrganizationCertificatesOrder = {
  ASC: 'ASC',
  DESC: 'DESC',
} as const;
