/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * Carmentis indexer API
 * Documentation for the Carmentis indexer API.
 * OpenAPI spec version: 1.0
 */

export type AppControllerGetBlocksSort = typeof AppControllerGetBlocksSort[keyof typeof AppControllerGetBlocksSort];


export const AppControllerGetBlocksSort = {
  height: 'height',
} as const;
