/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * Carmentis indexer API
 * Documentation for the Carmentis indexer API.
 * OpenAPI spec version: 1.0
 */
import type { AppControllerGetOrganizationCertificatesOrder } from './appControllerGetOrganizationCertificatesOrder';

export type AppControllerGetOrganizationCertificatesParams = {
/**
 * Sort order
 */
order?: AppControllerGetOrganizationCertificatesOrder;
/**
 * How many results to skip (for pagination)
 */
offset?: number;
/**
 * Maximum number of results
 */
limit?: number;
/**
 * Virtual blockchain ID
 */
vb_id: string;
};
