/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * Carmentis indexer API
 * Documentation for the Carmentis indexer API.
 * OpenAPI spec version: 1.0
 */
import type { AppControllerGetVotingPowersOrder } from './appControllerGetVotingPowersOrder';
import type { AppControllerGetVotingPowersSort } from './appControllerGetVotingPowersSort';

export type AppControllerGetVotingPowersParams = {
/**
 * Sort order
 */
order?: AppControllerGetVotingPowersOrder;
/**
 * Limit number of results
 */
limit?: number;
/**
 * Field on which the sort is applied
 */
sort?: AppControllerGetVotingPowersSort;
/**
 * Node virtual blockchain ID
 */
node_id?: string;
};
