/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * Carmentis indexer API
 * Documentation for the Carmentis indexer API.
 * OpenAPI spec version: 1.0
 */
import type { ObjectCountDto } from './objectCountDto';

export interface ChainResponseDto {
  version: string;
  network: string;
  earliestBlockHash: string;
  height: number;
  objectCounts: ObjectCountDto[];
}
