/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * Carmentis indexer API
 * Documentation for the Carmentis indexer API.
 * OpenAPI spec version: 1.0
 */

export interface MicroblockDto {
  hash: string;
  blockHeight: number;
  virtualBlockchainId: string;
  type: number;
  height: number;
  size: number;
  gas: number;
  /** Expressed in atomics */
  gasPrice: number;
  /** Returned only if include_content=true */
  content?: string;
}
