/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * Carmentis indexer API
 * Documentation for the Carmentis indexer API.
 * OpenAPI spec version: 1.0
 */
import type { MicroblockProofMicroblockDto } from './microblockProofMicroblockDto';
import type { MicroblockProofVirtualBlockchainDto } from './microblockProofVirtualBlockchainDto';
import type { ProofBlockDto } from './proofBlockDto';

export interface MicroblockProofWrapperDto {
  block: ProofBlockDto;
  microblock: MicroblockProofMicroblockDto;
  virtualBlockchain: MicroblockProofVirtualBlockchainDto;
}
