/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * Carmentis indexer API
 * Documentation for the Carmentis indexer API.
 * OpenAPI spec version: 1.0
 */

export interface OrganizationDto {
  virtualBlockchainId: string;
  accountId: string;
  name: string;
  city: string;
  countryCode: string;
  website: string;
}
