/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * Carmentis indexer API
 * Documentation for the Carmentis indexer API.
 * OpenAPI spec version: 1.0
 */
import type { OrganizationDto } from './organizationDto';

export interface OrganizationListResponseDto {
  items: OrganizationDto[];
  hasMore: boolean;
}
