/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * Carmentis indexer API
 * Documentation for the Carmentis indexer API.
 * OpenAPI spec version: 1.0
 */

export interface ValidatorNodeDto {
  virtualBlockchainId: string;
  organizationId: string;
  cometPublicKeyType: string;
  cometPublicKey: string;
  address: string;
  rpcEndpoint: string;
  currentVotingPower: number;
}
