/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * Carmentis indexer API
 * Documentation for the Carmentis indexer API.
 * OpenAPI spec version: 1.0
 */
import type { ValidatorNodeDtoStatus } from './validatorNodeDtoStatus';

export interface ValidatorNodeDto {
  virtualBlockchainId: string;
  organizationId: string;
  cometPublicKeyType: string;
  cometPublicKey: string;
  address: string;
  rpcEndpoint: string;
  currentVotingPower: number;
  status: ValidatorNodeDtoStatus;
  statusTimestamp: number;
  statusIsExpired: boolean;
}
