/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * Carmentis indexer API
 * Documentation for the Carmentis indexer API.
 * OpenAPI spec version: 1.0
 */

export interface VirtualBlockchainDto {
  virtualBlockchainId: string;
  height: number;
  type: number;
  creationTimestamp: number;
  modificationTimestamp: number;
  expirationTimestamp: number;
  lastMicroblockHash: string;
}
