/**
 * Generated by orval v8.13.0 🍺
 * Do not edit manually.
 * Carmentis indexer API
 * Documentation for the Carmentis indexer API.
 * OpenAPI spec version: 1.0
 */
import type { VotingPowerDto } from './votingPowerDto';

export interface VotingPowerListResponseDto {
  items: VotingPowerDto[];
  hasMore: boolean;
}
