/**
 * Generated by orval v8.14.0 🍺
 * Do not edit manually.
 * Carmentis indexer API
 * Documentation for the Carmentis indexer API.
 * OpenAPI spec version: 1.0
 */
import type {
  AccountHistoryListResponseDto,
  AccountListResponseDto,
  AccountProofResponseDto,
  AppControllerGetAccountHistoryParams,
  AppControllerGetAccountProofParams,
  AppControllerGetAccountsParams,
  AppControllerGetApplicationsParams,
  AppControllerGetBlocksParams,
  AppControllerGetGasPriceParams,
  AppControllerGetMicroblockProofParams,
  AppControllerGetMicroblocksParams,
  AppControllerGetNodeStatusParams,
  AppControllerGetOrganizationsParams,
  AppControllerGetValidatorNodesParams,
  AppControllerGetVirtualBlockchainsParams,
  AppControllerGetVotingPowersParams,
  AppControllerSearchParams,
  ApplicationListResponseDto,
  BlockListResponseDto,
  ChainResponseDto,
  GasPriceResponseDto,
  MicroblockListResponseDto,
  MicroblockProofResponseDto,
  NodeStatusResponseDto,
  OrganizationListResponseDto,
  SearchListResponseDto,
  ValidatorNodeListResponseDto,
  VirtualBlockchainListResponseDto,
  VotingPowerListResponseDto
} from './model';

import { customFetch } from './http-client/http-client';
export type appControllerGetRootResponse200 = {
  data: void
  status: 200
}

export type appControllerGetRootResponseSuccess = (appControllerGetRootResponse200) & {
  headers: Headers;
};
;

export type appControllerGetRootResponse = (appControllerGetRootResponseSuccess)

export const getAppControllerGetRootUrl = () => {




  return `/api/v1`
}

export const appControllerGetRoot = async ( options?: RequestInit): Promise<appControllerGetRootResponse> => {

  return customFetch<appControllerGetRootResponse>(getAppControllerGetRootUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type appControllerGetChainResponse200 = {
  data: ChainResponseDto
  status: 200
}

export type appControllerGetChainResponseSuccess = (appControllerGetChainResponse200) & {
  headers: Headers;
};
;

export type appControllerGetChainResponse = (appControllerGetChainResponseSuccess)

export const getAppControllerGetChainUrl = () => {




  return `/api/v1/chain`
}

export const appControllerGetChain = async ( options?: RequestInit): Promise<appControllerGetChainResponse> => {

  return customFetch<appControllerGetChainResponse>(getAppControllerGetChainUrl(),
  {
    ...options,
    method: 'GET'


  }
);}



export type appControllerGetGasPriceResponse200 = {
  data: GasPriceResponseDto
  status: 200
}

export type appControllerGetGasPriceResponseSuccess = (appControllerGetGasPriceResponse200) & {
  headers: Headers;
};
;

export type appControllerGetGasPriceResponse = (appControllerGetGasPriceResponseSuccess)

export const getAppControllerGetGasPriceUrl = (params?: AppControllerGetGasPriceParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/gas-price?${stringifiedParams}` : `/api/v1/gas-price`
}

export const appControllerGetGasPrice = async (params?: AppControllerGetGasPriceParams, options?: RequestInit): Promise<appControllerGetGasPriceResponse> => {

  return customFetch<appControllerGetGasPriceResponse>(getAppControllerGetGasPriceUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export type appControllerSearchResponse200 = {
  data: SearchListResponseDto
  status: 200
}

export type appControllerSearchResponseSuccess = (appControllerSearchResponse200) & {
  headers: Headers;
};
;

export type appControllerSearchResponse = (appControllerSearchResponseSuccess)

export const getAppControllerSearchUrl = (params: AppControllerSearchParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/search?${stringifiedParams}` : `/api/v1/search`
}

export const appControllerSearch = async (params: AppControllerSearchParams, options?: RequestInit): Promise<appControllerSearchResponse> => {

  return customFetch<appControllerSearchResponse>(getAppControllerSearchUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export type appControllerGetBlocksResponse200 = {
  data: BlockListResponseDto
  status: 200
}

export type appControllerGetBlocksResponseSuccess = (appControllerGetBlocksResponse200) & {
  headers: Headers;
};
;

export type appControllerGetBlocksResponse = (appControllerGetBlocksResponseSuccess)

export const getAppControllerGetBlocksUrl = (params?: AppControllerGetBlocksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/blocks?${stringifiedParams}` : `/api/v1/blocks`
}

export const appControllerGetBlocks = async (params?: AppControllerGetBlocksParams, options?: RequestInit): Promise<appControllerGetBlocksResponse> => {

  return customFetch<appControllerGetBlocksResponse>(getAppControllerGetBlocksUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export type appControllerGetMicroblocksResponse200 = {
  data: MicroblockListResponseDto
  status: 200
}

export type appControllerGetMicroblocksResponseSuccess = (appControllerGetMicroblocksResponse200) & {
  headers: Headers;
};
;

export type appControllerGetMicroblocksResponse = (appControllerGetMicroblocksResponseSuccess)

export const getAppControllerGetMicroblocksUrl = (params?: AppControllerGetMicroblocksParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/microblocks?${stringifiedParams}` : `/api/v1/microblocks`
}

export const appControllerGetMicroblocks = async (params?: AppControllerGetMicroblocksParams, options?: RequestInit): Promise<appControllerGetMicroblocksResponse> => {

  return customFetch<appControllerGetMicroblocksResponse>(getAppControllerGetMicroblocksUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export type appControllerGetMicroblockProofResponse200 = {
  data: MicroblockProofResponseDto
  status: 200
}

export type appControllerGetMicroblockProofResponseSuccess = (appControllerGetMicroblockProofResponse200) & {
  headers: Headers;
};
;

export type appControllerGetMicroblockProofResponse = (appControllerGetMicroblockProofResponseSuccess)

export const getAppControllerGetMicroblockProofUrl = (params: AppControllerGetMicroblockProofParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/microblock-proof?${stringifiedParams}` : `/api/v1/microblock-proof`
}

export const appControllerGetMicroblockProof = async (params: AppControllerGetMicroblockProofParams, options?: RequestInit): Promise<appControllerGetMicroblockProofResponse> => {

  return customFetch<appControllerGetMicroblockProofResponse>(getAppControllerGetMicroblockProofUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export type appControllerGetAccountsResponse200 = {
  data: AccountListResponseDto
  status: 200
}

export type appControllerGetAccountsResponseSuccess = (appControllerGetAccountsResponse200) & {
  headers: Headers;
};
;

export type appControllerGetAccountsResponse = (appControllerGetAccountsResponseSuccess)

export const getAppControllerGetAccountsUrl = (params?: AppControllerGetAccountsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/accounts?${stringifiedParams}` : `/api/v1/accounts`
}

export const appControllerGetAccounts = async (params?: AppControllerGetAccountsParams, options?: RequestInit): Promise<appControllerGetAccountsResponse> => {

  return customFetch<appControllerGetAccountsResponse>(getAppControllerGetAccountsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export type appControllerGetAccountHistoryResponse200 = {
  data: AccountHistoryListResponseDto
  status: 200
}

export type appControllerGetAccountHistoryResponseSuccess = (appControllerGetAccountHistoryResponse200) & {
  headers: Headers;
};
;

export type appControllerGetAccountHistoryResponse = (appControllerGetAccountHistoryResponseSuccess)

export const getAppControllerGetAccountHistoryUrl = (params?: AppControllerGetAccountHistoryParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/account-history?${stringifiedParams}` : `/api/v1/account-history`
}

export const appControllerGetAccountHistory = async (params?: AppControllerGetAccountHistoryParams, options?: RequestInit): Promise<appControllerGetAccountHistoryResponse> => {

  return customFetch<appControllerGetAccountHistoryResponse>(getAppControllerGetAccountHistoryUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export type appControllerGetAccountProofResponse200 = {
  data: AccountProofResponseDto
  status: 200
}

export type appControllerGetAccountProofResponseSuccess = (appControllerGetAccountProofResponse200) & {
  headers: Headers;
};
;

export type appControllerGetAccountProofResponse = (appControllerGetAccountProofResponseSuccess)

export const getAppControllerGetAccountProofUrl = (params: AppControllerGetAccountProofParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/account-proof?${stringifiedParams}` : `/api/v1/account-proof`
}

export const appControllerGetAccountProof = async (params: AppControllerGetAccountProofParams, options?: RequestInit): Promise<appControllerGetAccountProofResponse> => {

  return customFetch<appControllerGetAccountProofResponse>(getAppControllerGetAccountProofUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export type appControllerGetOrganizationsResponse200 = {
  data: OrganizationListResponseDto
  status: 200
}

export type appControllerGetOrganizationsResponseSuccess = (appControllerGetOrganizationsResponse200) & {
  headers: Headers;
};
;

export type appControllerGetOrganizationsResponse = (appControllerGetOrganizationsResponseSuccess)

export const getAppControllerGetOrganizationsUrl = (params?: AppControllerGetOrganizationsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/organizations?${stringifiedParams}` : `/api/v1/organizations`
}

export const appControllerGetOrganizations = async (params?: AppControllerGetOrganizationsParams, options?: RequestInit): Promise<appControllerGetOrganizationsResponse> => {

  return customFetch<appControllerGetOrganizationsResponse>(getAppControllerGetOrganizationsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export type appControllerGetApplicationsResponse200 = {
  data: ApplicationListResponseDto
  status: 200
}

export type appControllerGetApplicationsResponseSuccess = (appControllerGetApplicationsResponse200) & {
  headers: Headers;
};
;

export type appControllerGetApplicationsResponse = (appControllerGetApplicationsResponseSuccess)

export const getAppControllerGetApplicationsUrl = (params?: AppControllerGetApplicationsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/applications?${stringifiedParams}` : `/api/v1/applications`
}

export const appControllerGetApplications = async (params?: AppControllerGetApplicationsParams, options?: RequestInit): Promise<appControllerGetApplicationsResponse> => {

  return customFetch<appControllerGetApplicationsResponse>(getAppControllerGetApplicationsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export type appControllerGetValidatorNodesResponse200 = {
  data: ValidatorNodeListResponseDto
  status: 200
}

export type appControllerGetValidatorNodesResponseSuccess = (appControllerGetValidatorNodesResponse200) & {
  headers: Headers;
};
;

export type appControllerGetValidatorNodesResponse = (appControllerGetValidatorNodesResponseSuccess)

export const getAppControllerGetValidatorNodesUrl = (params?: AppControllerGetValidatorNodesParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/validator-nodes?${stringifiedParams}` : `/api/v1/validator-nodes`
}

export const appControllerGetValidatorNodes = async (params?: AppControllerGetValidatorNodesParams, options?: RequestInit): Promise<appControllerGetValidatorNodesResponse> => {

  return customFetch<appControllerGetValidatorNodesResponse>(getAppControllerGetValidatorNodesUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export type appControllerGetNodeStatusResponse200 = {
  data: NodeStatusResponseDto
  status: 200
}

export type appControllerGetNodeStatusResponseSuccess = (appControllerGetNodeStatusResponse200) & {
  headers: Headers;
};
;

export type appControllerGetNodeStatusResponse = (appControllerGetNodeStatusResponseSuccess)

export const getAppControllerGetNodeStatusUrl = (params: AppControllerGetNodeStatusParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/node-status?${stringifiedParams}` : `/api/v1/node-status`
}

export const appControllerGetNodeStatus = async (params: AppControllerGetNodeStatusParams, options?: RequestInit): Promise<appControllerGetNodeStatusResponse> => {

  return customFetch<appControllerGetNodeStatusResponse>(getAppControllerGetNodeStatusUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export type appControllerGetVirtualBlockchainsResponse200 = {
  data: VirtualBlockchainListResponseDto
  status: 200
}

export type appControllerGetVirtualBlockchainsResponseSuccess = (appControllerGetVirtualBlockchainsResponse200) & {
  headers: Headers;
};
;

export type appControllerGetVirtualBlockchainsResponse = (appControllerGetVirtualBlockchainsResponseSuccess)

export const getAppControllerGetVirtualBlockchainsUrl = (params?: AppControllerGetVirtualBlockchainsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/virtual-blockchains?${stringifiedParams}` : `/api/v1/virtual-blockchains`
}

export const appControllerGetVirtualBlockchains = async (params?: AppControllerGetVirtualBlockchainsParams, options?: RequestInit): Promise<appControllerGetVirtualBlockchainsResponse> => {

  return customFetch<appControllerGetVirtualBlockchainsResponse>(getAppControllerGetVirtualBlockchainsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}



export type appControllerGetVotingPowersResponse200 = {
  data: VotingPowerListResponseDto
  status: 200
}

export type appControllerGetVotingPowersResponseSuccess = (appControllerGetVotingPowersResponse200) & {
  headers: Headers;
};
;

export type appControllerGetVotingPowersResponse = (appControllerGetVotingPowersResponseSuccess)

export const getAppControllerGetVotingPowersUrl = (params?: AppControllerGetVotingPowersParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/voting-powers?${stringifiedParams}` : `/api/v1/voting-powers`
}

export const appControllerGetVotingPowers = async (params?: AppControllerGetVotingPowersParams, options?: RequestInit): Promise<appControllerGetVotingPowersResponse> => {

  return customFetch<appControllerGetVotingPowersResponse>(getAppControllerGetVotingPowersUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}
